services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 1234:5432
    env_file:
      - ./back-end/.env
    volumes:
      - db_drivenops:/var/lib/postgresql/data

  drivenops:
    container_name: back_drivenops
    build: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - ./back-end/.env

  drivenops_frontend:
    container_name:   drivenops_frontend
    build: ./front-end
    ports: 
      - 3001:3000
    depends_on:
      - drivenops
    env_file:
      - ./front-end/.env
    
volumes:
  db_drivenops: