services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 1235:5432
    env_file:
      - ./back-end/.env.test

  drivenops:
    container_name: image_drivenops
    build: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - ./back-end/.env.test