services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 1235:5432
    env_file:
      - ./back-end/.env
    volumes:
      - db_drivenops:/var/lib/postgresql/data

  drivenops:
    container_name: drivenops
    build: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - ./back-end/.env

  react_sorteador_app_live:
    container_name: react_sorteador_app_live
    build: ./front-end
    image: react_sorteador_app_live_image
    volumes:
      - build_react:/var/www/html

  nginx_sorteador_app_live:
    container_name: nginx_sorteador_app_live
    build: ./nginx
    image: nginx_sorteador_app_live_image
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_drivenops
      - drivenops
      - react_sorteador_app_live

volumes:
  db_drivenops:
  build_react: