services:
  db_drivenops:
    image: postgres
    container_name: db_drivenops
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  drivenops:
    container_name: back_drivenops
    build: .
    ports: 
      - 5000:5000
    depends_on:
      - db_drivenops
    env_file:
      - .env.test