name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER_TEST }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_TEST }}
        envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB_TEST }}
        envkey_DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
        directory: /back-end
        file-name: .env.test
        fail_on_empty: true
    - name: Run tests
      run: docker-compose -f docker-compose.test.yml run drivenops npm run test